# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18eDOTFq98Mkfo0S71qB4-bo2BFFOxecd
"""

import streamlit as st
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import joblib
import json
import os


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="TrustFed-CKD",
    page_icon="🩺",
    layout="wide"
)


# ============================================================
# MODEL DEFINITION
# Must match the model trained in Colab
# ============================================================

class CKDModel(nn.Module):

    def __init__(self, input_size):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(input_size, 32),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(32, 16),
            nn.ReLU(),

            nn.Linear(16, 1)
        )

    def forward(self, x):

        return self.network(x).squeeze(1)


# ============================================================
# LOAD MODEL FILES
# ============================================================

MODEL_DIR = "trustfed_ckd_model"


@st.cache_resource
def load_model():

    # Load feature names
    with open(
        os.path.join(MODEL_DIR, "features.json"),
        "r"
    ) as f:

        features = json.load(f)


    # Load threshold
    with open(
        os.path.join(MODEL_DIR, "threshold.json"),
        "r"
    ) as f:

        threshold_data = json.load(f)

    threshold = threshold_data["threshold"]


    # Load scaler
    scaler = joblib.load(
        os.path.join(
            MODEL_DIR,
            "scaler.pkl"
        )
    )


    # Create model
    model = CKDModel(
        len(features)
    )


    # Load trained global model
    model.load_state_dict(
        torch.load(
            os.path.join(
                MODEL_DIR,
                "global_model.pth"
            ),
            map_location=torch.device("cpu")
        )
    )

    model.eval()


    return model, scaler, features, threshold


model, scaler, feature_columns, threshold = load_model()


# ============================================================
# LOAD TRUST SCORES
# ============================================================

@st.cache_data
def load_trust_scores():

    path = os.path.join(
        MODEL_DIR,
        "hospital_trust_scores.csv"
    )

    return pd.read_csv(path)


trust_df = load_trust_scores()


# ============================================================
# HEADER
# ============================================================

st.title("🩺 TrustFed-CKD")

st.subheader(
    "Trust-Aware Federated Learning Framework "
    "for CKD Risk Prediction"
)

st.markdown(
    """
This prototype demonstrates a federated-learning framework
using three simulated hospital clients.

**Raw patient data remains at the hospital level during
federated training. Only model parameters are aggregated
through FedAvg.**
"""
)


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("Navigation")

page = st.sidebar.radio(
    "Select Module",
    [
        "🏠 Dashboard",
        "🏥 Hospital Trust",
        "🩺 CKD Prediction",
        "📊 Model Performance"
    ]
)


# ============================================================
# DASHBOARD
# ============================================================

if page == "🏠 Dashboard":

    st.header("Federated Learning Dashboard")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Hospital Clients",
            "3"
        )

    with col2:
        st.metric(
            "Federated Method",
            "FedAvg"
        )

    with col3:
        st.metric(
            "Decision Threshold",
            f"{threshold:.2f}"
        )

    with col4:
        st.metric(
            "Model Type",
            "Neural Network"
        )


    st.divider()

    st.subheader("Federated Architecture")

    st.markdown(
        """
        ### 🏥 Hospital A
        Local Model Training

        ↓

        ### 🏥 Hospital B
        Local Model Training

        ↓

        ### 🏥 Hospital C
        Local Model Training

        ↓

        ### 🔄 FedAvg Aggregation

        ↓

        ### 🌐 Global CKD Model
        """
    )

    st.info(
        "The three hospitals shown here are simulated "
        "clients created from the NHANES dataset."
    )


# ============================================================
# HOSPITAL TRUST
# ============================================================

elif page == "🏥 Hospital Trust":

    st.header("Hospital Trust Analysis")

    st.write(
        "Client-level performance indicators used to "
        "calculate the prototype trust score."
    )

    display_df = trust_df.copy()

    # Convert values to percentage where appropriate
    percentage_columns = [
        "Accuracy",
        "Precision",
        "Recall",
        "F1",
        "ROC_AUC"
    ]

    for col in percentage_columns:

        if col in display_df.columns:

            display_df[col] = (
                display_df[col] * 100
            ).round(2)


    st.dataframe(
        display_df,
        use_container_width=True,
        hide_index=True
    )


    st.subheader("Trust Scores")

    trust_chart = trust_df[
        ["Hospital", "Trust_Score"]
    ].set_index("Hospital")

    st.bar_chart(
        trust_chart
    )


    st.markdown(
        """
### Trust Score Formula

The prototype trust score is calculated as:

**Trust Score = 0.40 × F1 + 0.30 × Recall + 0.30 × ROC-AUC**

This is a performance-based trust indicator for the
research prototype and is not a clinical or security
certification.
"""
    )


# ============================================================
# CKD PREDICTION
# ============================================================

elif page == "🩺 CKD Prediction":

    st.header("CKD Risk Prediction")

    st.write(
        "Enter patient information to obtain a prediction "
        "from the global federated model."
    )


    col1, col2, col3 = st.columns(3)


    with col1:

        age = st.number_input(
            "Age",
            min_value=18,
            max_value=100,
            value=50
        )

        gender = st.selectbox(
            "Gender",
            [
                "Male",
                "Female"
            ]
        )

        bmi = st.number_input(
            "BMI",
            min_value=10.0,
            max_value=60.0,
            value=25.0
        )

        systolic_bp = st.number_input(
            "Systolic BP",
            min_value=70.0,
            max_value=250.0,
            value=120.0
        )


    with col2:

        diastolic_bp = st.number_input(
            "Diastolic BP",
            min_value=40.0,
            max_value=150.0,
            value=80.0
        )

        bun = st.number_input(
            "BUN",
            min_value=0.0,
            max_value=150.0,
            value=15.0
        )

        glucose = st.number_input(
            "Glucose",
            min_value=40.0,
            max_value=500.0,
            value=100.0
        )

        albumin = st.number_input(
            "Albumin",
            min_value=0.0,
            max_value=10.0,
            value=4.0
        )


    with col3:

        globulin = st.number_input(
            "Globulin",
            min_value=0.0,
            max_value=10.0,
            value=3.0
        )

        diabetes = st.selectbox(
            "Diabetes",
            [
                "No",
                "Yes"
            ]
        )

        hypertension = st.selectbox(
            "Hypertension",
            [
                "No",
                "Yes"
            ]
        )

        acr = st.number_input(
            "ACR",
            min_value=0.0,
            max_value=5000.0,
            value=20.0
        )


    predict_button = st.button(
        "🔍 Predict CKD Risk",
        type="primary",
        use_container_width=True
    )


    if predict_button:

        # Convert gender to NHANES encoding
        gender_value = (
            1 if gender == "Male"
            else 2
        )

        diabetes_value = (
            1 if diabetes == "Yes"
            else 0
        )

        hypertension_value = (
            1 if hypertension == "Yes"
            else 0
        )


        # Create input in EXACT feature order
        patient_data = pd.DataFrame(
            [[
                age,
                gender_value,
                bmi,
                systolic_bp,
                diastolic_bp,
                bun,
                glucose,
                albumin,
                globulin,
                diabetes_value,
                hypertension_value,
                acr
            ]],
            columns=feature_columns
        )


        # Scale
        scaled_data = scaler.transform(
            patient_data
        )


        # Convert to tensor
        input_tensor = torch.tensor(
            scaled_data,
            dtype=torch.float32
        )


        # Prediction
        with torch.no_grad():

            logit = model(
                input_tensor
            )

            probability = torch.sigmoid(
                logit
            ).item()


        prediction = (
            probability >= threshold
        )


        st.divider()

        st.subheader(
            "Prediction Result"
        )


        col1, col2 = st.columns(2)


        with col1:

            st.metric(
                "CKD Risk Probability",
                f"{probability * 100:.2f}%"
            )


        with col2:

            if prediction:

                st.error(
                    "⚠️ CKD Risk Detected"
                )

            else:

                st.success(
                    "✅ Low CKD Risk"
                )


        st.progress(
            min(probability, 1.0)
        )


        st.info(
            f"Classification threshold: "
            f"{threshold:.2f}"
        )


        st.warning(
            "This application is a research prototype "
            "and is not a medical diagnostic tool."
        )


# ============================================================
# MODEL PERFORMANCE
# ============================================================

elif page == "📊 Model Performance":

    st.header(
        "Global Federated Model Performance"
    )

    # These are the values obtained from the
    # current global test evaluation.

    accuracy = 0.6900
    precision = 0.1662
    recall = 0.8857
    f1 = 0.2799
    roc_auc = 0.8614


    col1, col2, col3, col4, col5 = st.columns(5)


    with col1:
        st.metric(
            "Accuracy",
            f"{accuracy * 100:.2f}%"
        )


    with col2:
        st.metric(
            "Precision",
            f"{precision * 100:.2f}%"
        )


    with col3:
        st.metric(
            "Recall",
            f"{recall * 100:.2f}%"
        )


    with col4:
        st.metric(
            "F1 Score",
            f"{f1 * 100:.2f}%"
        )


    with col5:
        st.metric(
            "ROC-AUC",
            f"{roc_auc:.4f}"
        )


    st.divider()


    st.subheader(
        "Global Test Confusion Matrix"
    )


    confusion = pd.DataFrame(
        {
            "Predicted Low Risk": [648, 8],
            "Predicted CKD Risk": [311, 62]
        },
        index=[
            "Actual Low Risk",
            "Actual CKD Risk"
        ]
    )


    st.dataframe(
        confusion,
        use_container_width=True
    )


    st.subheader(
        "Interpretation"
    )

    st.write(
        """
The current federated model demonstrates high sensitivity
for the CKD-risk class, with a global test recall of
approximately 88.57% at the 0.50 threshold.

Because the dataset is highly imbalanced, precision,
recall, F1-score and ROC-AUC should be considered alongside
accuracy.
"""
    )


    st.subheader(
        "Threshold Analysis"
    )

    threshold_data = pd.DataFrame(
        {
            "Threshold": [
                0.50,
                0.55,
                0.60,
                0.65,
                0.70
            ],

            "Accuracy": [
                0.6093,
                0.7568,
                0.8435,
                0.8795,
                0.9125
            ],

            "Precision": [
                0.1438,
                0.2122,
                0.2714,
                0.3099,
                0.3571
            ],

            "Recall": [
                0.9571,
                0.9000,
                0.7714,
                0.6286,
                0.3571
            ],

            "F1": [
                0.2500,
                0.3433,
                0.4015,
                0.4151,
                0.3571
            ]
        }
    )

    st.dataframe(
        threshold_data,
        use_container_width=True,
        hide_index=True
    )

    st.info(
        "The selected deployment threshold is 0.65, "
        "which provided the highest F1-score in the "
        "threshold analysis performed in the Colab notebook."
    )